### ISSUE TITLE
Error handling for GraphQL probably needs to be looser

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/biz-ops-client#1]
A good response may still contain some errors by design (in practice this doesn't really happen to us as we're not a traditional GraphQL api blending lots of different sources... yet). I think the logic should be 

```js
if (data) {
   // maybe do something to log/handle errors. probably needs to be user defined as only the application knows which errors matter
  // Maybe needs an option to say what sort of ignore/not ignore option to use
   // return ok response
}
```

https://github.com/Financial-Times/biz-ops-client/blob/59821c686f7d6f90a7342128b68cd2dd402fcea8/lib/api/graphQL.js#L33-L43

Intersting (though perhaps not 100% relevant... certainly not an approach we can take without some BIIIIG changes ) talk on graphql error handling https://www.youtube.com/watch?v=A5-H6MtTvqk.

**Comment by i-like-robots** [comment]
Yes I agree. The original implementation this package is based on does not error and as an end user I'm not sure this behavior is wanted... I only want things to error if I they have to! Perhaps it could be available as an option á la "strict mode"

**Comment by wheresrhys** [comment]
yes, 'strict mode' as a label to distinguish between these feels perfect

**Comment by i-like-robots** [comment]
Added in 93e537cd2047537178d1bab044140dd2600348c7
