### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/biz-ops-client#12]
How does this library know which level of rate limit it is required to use? 😟 

As a client of the raw API I could opt for any rate between 1 and the 50 or so requests per second that my key for the API allows. If I received failures during testing I could then reduce the rate or ask for an updated key.

I'm currently getting `rate limited exceeded` which suggests the rate permitted by the library exceeds the rate for my key.

It feels like this library should allow me to pass in a rate and/or read my key to find my rate. 😄

**Comment by i-like-robots** [comment]
The rate was decided based on this conversation: https://github.com/Financial-Times/biz-ops-client/pull/8#discussion_r470066932

I'll amend to allow this rate to be configurable.

**Comment by GeoffThorpeFT** [comment]
Many thanks

**Comment by i-like-robots** [comment]
Resolved by #13
