### ISSUE TITLE
Change the default graphQL endpoint error mode to strict:true

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/biz-ops-client#23]
Currently all `graphql` endpoint requests (both `get` and `post`) will ignore graphql errors such as the omission of the `code` property for resolved fields unless you explicitly set the `strict` param to `true`.

Shouldn't we reverse this so you have to explicitly say you want to ignore errors?

i.e.the default should be `strict:true`

**Comment by wheresrhys** [comment]
Also see https://github.com/Financial-Times/biz-ops-search/issues/93

**Comment by GeoffThorpeFT** [comment]
This issue has just appeared again in a way that highlights a significant difference between graphQL's `no throw` policy and the concept of `bad query syntax`.

We have code in problem-hub for problem definitions that runs the user's query and then passes the resulting data down to the jsonata mapping. It uses biz-ops client as follows:

```
		const response = await client.graphQL.post(query, params);
		const dataTypes = Object.keys(response);
		if (dataTypes.length > 1) {
			throw new Error(
				`Query has output more than one dataset: ${dataTypes}`,
			);
		}
		const records = response[dataTypes[0]];
```

The above is enclosed in a `try/catch` so errors in the graphql will be caught ... but no errors are thrown since we dont use `strict`. We get `undefined` since the client only returns the `data` object;  query syntax errors only populate the `error` object.

So all our users could be running queries with syntax errors but they dont see any errors - and probably just treat `undefined ` as an empty array.  We do that in Biz Ops admin home screen https://github.com/Financial-Times/biz-ops-admin/blob/main/src/controllers/home.js#L72C1-L76C41 !

To be clear valid queries **always** return an array (obeying graphql policy) only syntax errors return `undefined`.
