### ISSUE TITLE
A simpler way to get a single record with graphQL v2

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/biz-ops-client#28]
The migration to the new supported Neo4j GraphQL library has triggered some breaking changes. To provide our customers with a safe path to upgrade we now have a v1 and v2 graphql endpoints in the Biz Ops API via the use of a header.

However, this Biz Ops Client library, at v0.8.0, only provides the v2 interface.

That is fine for users who wish to make ALL the necessary syntax and response changes in one go. But, the read of a single record has changed a lot!

Before, when the response was `null` or a single object of results, you could do this:
```
		const { Team: team } = await getBizOpsClient().graphQL.get(
			teamQuery(teamCode),
		);

		if (!team) {
			throw httpErrors(404, `Team ${teamCode} does not exist`);
		}

		props.teamCode = teamCode;
```

Now that the result is always an array (of zero length if the key is not present) you have to do this:
```
		const { teams } = await getBizOpsClient().graphQL.get(
			teamQuery(teamCode),
		);

		if (!teams.length) {
			throw httpErrors(404, `Team ${teamCode} does not exist`);
		}

		const team = teams[0];
		props.teamCode = teamCode;
```

Should we consider adding a `.getOne()` or `.getOnly()`  method which mimics the original v1 approach of returning `null` or a single `object` to this Biz-Ops-Client library so the users can just replace the function call instead of the whole pattern?

We could then throw an error within the library if the getOne() or getOnly actually returns more than one record.

**Comment by wheresrhys** [comment]
I think it's possible to improve this situation via something like defining [custom resolvers](https://neo4j.com/docs/graphql-manual/current/ogm/examples/custom-resolvers/) for e.g. `Query {system }`.

In the example linked to above it uses the neo4j-graphql OGM's find method to fetch one record. We can probably do something similar to implement a `get a single record` resolver in the api. Worth a spike to see how easy it is to write one for a single type.

**Comment by GeoffThorpeFT** [comment]
Another quick look at `getOne` suggests its not that easy to implement with biz-ops-client since that client library currently returns whatever it gets from the graphql request. That request may be more than one query.  It wont know which one to reduce to a single object.

Unfortunately implementation in a resolver is almost as complex as it needs to be aware of all the filtering options to be able to get just the record the user wants (its not just a simple case of a `System {code, name }` query ). We have never written a complex resolved like that with full filtering!  In fact such a resolver would almost be a clone of the one written by neo4j themselves.

Can we inherit from their resolver and just send back a single record?
