### ISSUE TITLE
Allow user defined logger

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/biz-ops-client#3]
Seeing in risk register that wraps the client in an error handler just for the purposes of logging  https://github.com/Financial-Times/risk-register/pull/60/files#diff-0a37783321a3b7ddb629037a4d90f461R24-R40 

Feels like an opportunity to move this upstream and avoid repeating implementations.

Though maybe this is a bad idea. Thoughts?

**Comment by i-like-robots** [comment]
My first thought was yes, and I did have a `logger` option,  but I removed it as I wasn't sure of the value added - any errors will still need to be caught and handled, and that's where any logging should be anyway.
