### ISSUE TITLE
Consider caching graphql responses

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/biz-ops-client#38]
A number of the uses of this Biz Ops Client module are to validate a type or type/code combination.  Examples include requests from both the Biz Ops Metrics API and the Problem Hub API.

Those requests come at high volume within a short space of time and require the callers to construct a graphql query.  An example is the repeated validation of the `AWSResource` type when creating 5000 problems.

Would it be possible to cache graphql responses within this client?

**Comment by GeoffThorpeFT** [comment]
Caching would be an alternative to a similar idea https://github.com/Financial-Times/biz-ops-client/issues/37 - HEAD requests for types

**Comment by wheresrhys** [comment]
I think that's scope creep for the client. And it's probably far better for the app that needs a cache to be in charge of defining exactly how it behaves, and there are ample, easy to use libraries to achieve this
